### ISSUE TITLE
Unhandled NoMethodError if invisible_captcha_timestamp not in session

### ISSUE THREAD

**Issue by webit-dev** [markets/invisible_captcha#10]
[This Line](https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb#L41) throws
``NoMethodError: undefined method` -@' for nil:NilClass``
because you can not  calculate `Time.zone.now - timestamp` when timestamp is nil.
A possible solution could be to split the condition to:

```ruby
    def invisible_captcha_timestamp?(options = {})
      timestamp = session[:invisible_captcha_timestamp]
      if timestamp
        time_to_submit  = Time.zone.now - timestamp

        # Consider as spam if form submitted too quickly
        if time_to_submit < InvisibleCaptcha.timestamp_threshold
          logger.warn("Potential spam detected for IP #{request.env['REMOTE_ADDR']}. Invisible Captcha timestamp threshold not reached (took #{time_to_submit.to_i}s).")
          return true
        end
      end
      false
    end
```

Maybe there are other suggestions?

**Comment by markets** [comment]
Hi @webit-dev, thanks for reporting!

Yes, you're right, it can crash... I'm preparing a new release here (you're using master branch): #8

I think I would write it like:

```ruby
timestamp = session[:invisible_captcha_timestamp]
return unless timestamp
```

Do you want to help me with this and send a PR (to `fix_ci` branch, just in case)?

**Comment by webit-dev** [comment]
I made a pull request from fix_ci branch like you suggested: #11

**Comment by kikito** [comment]
I believe this can be closed.

**Comment by markets** [comment]
Yep, the PR has been merged to the next minor release branch. So, I'm going to close this. Thanks Enrique!
