### ISSUE TITLE
Adding recaptcha to handle the chrome auto fill bug

### ISSUE THREAD

**Issue by AneurinPartridge** [markets/invisible_captcha#103]
Trying to add a secondary recaptcha which is shown upon failing the invisible captcha, this allows our users a "second chance" to fill out a normal captcha to avoid having their web message on our system blocked and falsely marked as spam, the only issue we're having is that we're losing the parameters for our web message upon allowing it, we've got the honeypot set before the create action and are hoping that failing the honeypot but passing the normal captcha will allow the message to go through, this is failing however due to us losing our parameters(which I believe is due to the honeypot's handling), I'm fairly new to Rails and am an apprentice so it would be appreciated on any guidance 😅

**Comment by markets** [comment]
Hi @AneurinPartridge,

I think you should use a custom `on_spam` callback, so you will be able to define a custom redirect with custom parameters that you can handle at that point:

```ruby
class TopicsController < ApplicationController
  invisible_captcha only: :create, on_spam: :your_spam_callback_method

  private

  def your_spam_callback_method
    # Your custom redirect, with custom params.
    # You can also check for the `params` object, or inspect the `request` object: request.query_parameters.
    redirect_to root_path(my_param: 'my_value')
  end
end
```

**Comment by AneurinPartridge** [comment]
So we use the custom on_spam callback which triggers the recaptcha and the second time around will check the value of the recaptcha if it's present, the problem seems to be with my understanding of the invisible captcha

def enable_captcha
    if params["g-recaptcha-response"]
      if recaptcha_check
        @passed = true
        head(200)
        create_with_found_or_new_conversation
      else
        @passed = false
        render "web_messages/bot_success"
      end
    else
      @captcha = true
      @web_message ||= WebMessage.new
      @web_message.sender = current_user || StudentUser.new
      render :new
    end
  end

**Comment by markets** [comment]
Hey @AneurinPartridge just to be clear, this gem `invisible_captcha` has no relation with `recaptcha` or the `recaptcha_check` things.

**Comment by AneurinPartridge** [comment]
I am well aware, it seems to be that the response is still being blocked by the invisible captcha's handling

**Comment by markets** [comment]
The gem did some params cleaning, but only for the honeypot attribute, here (when there is no "honeypot spam"):

https://github.com/markets/invisible_captcha/blob/35a7f4f0b82a93967a0ac498f95be558898b71ef/lib/invisible_captcha/controller_ext.rb#L95-L97

Apart from that, the gem doesn't delete params in any other place of the code. 

Did you see any message in the log with the following pattern?

https://github.com/markets/invisible_captcha/blob/35a7f4f0b82a93967a0ac498f95be558898b71ef/lib/invisible_captcha/controller_ext.rb#L112

Just an idea to try (it's hard to say without seeing/debugging the code): maybe you are losing somehow the instance and you need to re-initialize this object with the params:

```ruby
@web_message ||= WebMessage.new(body: params[:body])
```
