### ISSUE TITLE
By using I18n.with_locale(..)  in app_controller action is not called

### ISSUE THREAD

**Issue by tclaus** [markets/invisible_captcha#107]
In my sewing I use the (recommended) ' I18n.with_locale(locale, &action)'  code to reliable set the user language got by the request. 

This is the last call, before any parameters are processed from a method (create in my case). Do I something wrong? 
Any recommendations for this? 
<img width="641" alt="Bildschirmfoto 2022-03-14 um 08 13 24" src="https://user-images.githubusercontent.com/501326/158122579-1d8a62ac-25b8-4d52-8fe1-6fe82585fdb9.png">

**Comment by markets** [comment]
Sorry @tclaus I don't understand what's the issue link with this gem? Could you please clarify?

**Comment by tclaus** [comment]
First of all, I have used the gem as describes in the doc. In the Controller I have added 
`invisible_captcha only: %i[create update], honeypot: :subtitle` right in the top in the class.
This works as expected. When the first method called in this controller , the captcha field is filtered out. 

But: In the application controller I have added a 'around_action' to set the locale in the application controller: 
```
class ApplicationController < ActionController::Base
  around_action :set_locale
...
  def set_locale(&action)
  ...
    I18n.with_locale(locale, &action)
  end
```

With this background, I discovered that in the relevant controller, the 'invisible_captcha' callback is not called. 

Not an issue with this gem, surely, but How can I get to use a 'around_action' _and_ the captcha?

**Comment by markets** [comment]
Is that code open source? Are you able to reproduce it inside an empty Rails app? It's really hard to debug code without having access to it, it could be caused by several reasons (even by other gems or callbacks). I'm using this gem in multiple apps, with `around_action`s too, with no problems.
