### ISSUE TITLE
Option with dynamic honeypot (collection of default honeypots) does not use scope

### ISSUE THREAD

**Issue by testa19** [markets/invisible_captcha#110]
The builder always creates a field with a scope
`@template.invisible_captcha(honeypot, self.object_name, options)`

But controller does not look at scope looking for `default_honeypot` param
```
if params[honeypot].present? || params.dig(scope, honeypot).present?
  ...
else
  if params[default_honeypot].present?
...
```

**Comment by markets** [comment]
Hi @testa19, yes that's the "expected" behavior right now when using the form helper (`form.invisible_captcha`) with an object. If you want to use the default collection, you can still use the raw view helper:

```html+erb
<%= form_for(Topic.new) do |f| %>
  <%= invisible_captcha %> 
<% end %>
```

Going to close as duplicated of #71.
