### ISSUE TITLE
Potential spam detected for IP 127.0.0.1. Invisible Captcha spinner value mismatch

### ISSUE THREAD

**Issue by ATEKVMEHTA** [markets/invisible_captcha#112]
I am using the latest version of **invisible_captcha** with **ruby 3.0.1** and **rails 6.1.6**

here is my form:

```
<form action="/contact" method="post">
    <%= invisible_captcha %>
    <input type="text">
    <input type="submit" value="submit">
 </form>
```

here is my controller:

```
class UnimedController < ApplicationController
  invisible_captcha only: [:contact]
  skip_before_action :verify_authenticity_token, :only => [:contact]

  def contact
    redirect_to root_path
  end
end
```

I am using a local server. @markets

**Comment by markets** [comment]
Hmm 🤔 weird, this works fine on my apps and also in our CI... Could you please inspect the generate HTML for that form? It should contain a hidden field with the "spinner" value.

This warn comes from:

https://github.com/markets/invisible_captcha/blob/8f1f6d478eae8e3c59f049493faf2160d12d583f/lib/invisible_captcha/controller_ext.rb#L75

**Comment by markets** [comment]
hey @ATEKVMEHTA 👋🏼 going to close this one for now... I can't help further without more details or a reproducible app. Please, re-open in case you can provide that info.
