### ISSUE TITLE
Markup not valid when run through HTML validator

### ISSUE THREAD

**Issue by timokleemann** [markets/invisible_captcha#114]
Is there a way to **remove** the `autocomplete="off"` attribute from the hidden field inputs and to move the `<style media="screen">` tags somewhere else?

This gem has saved me from an awful lot of spam over the last couple of years but unfortunately, in its latest version, a lot of the markup it produces is not valid: 

https://validator.w3.org/nu/?doc=https://www.billingengine.com

(Click on "Message filtering" and uncheck "Warnings" and "Info messages" to see the errors that really matter.)

How can this be fixed?

If I am not mistaken, none of these errors occurred in a previous version of this gem (don't remember which one exactly, though). Would downgrading to it possibly fix all these issues?

**Comment by markets** [comment]
Hi @timokleemann 👋🏼 

> Is there a way to remove the autocomplete="off" attribute from the hidden field

No, unfortunately there is no way to remove this attribute right now

> move the <style media="screen"> tags somewhere else

Yes, check the `injectable_styles` option: https://github.com/markets/invisible_captcha#plugin-options

> If I am not mistaken, none of these errors occurred in a previous version of this gem (don't remember which one exactly, though). Would downgrading to it possibly fix all these issues?

If you know what are the previous version you were using, you can check the [CHANGELOG](https://github.com/markets/invisible_captcha/blob/master/CHANGELOG.md) and compare both versions. You can also check source code changes between versions using the GH compare feature, example (from v1.1.0 to v2.0.0): https://github.com/markets/invisible_captcha/compare/v1.1.0...v2.0.0.

**Comment by timokleemann** [comment]
Hey @markets, thanks for getting back to me so quickly.

I think I figured it out. The issue can be solved by setting `config.injectable_styles = true` in an initializer. This will render all honeypot input fields as `type='text'` (rather than the default `type='hidden'`). This is OK for the [markup validator](https://validator.w3.org/nu/?doc=https://www.billingengine.com) since it allows `autocomplete='false'` on text fields (but not on hidden fields).

Just make sure you include `<%= invisible_captcha_styles %>` somewhere in your views, e.g. in `layout.rb`, **OR** include your own CSS like this to hide the honeypot fields:

```
[class^="favorite_"] {
	position: absolute!important;
	top: -9999px;
	left:-9999px;
}
```

(My CSS rule starts with `favorite_` since all my honeypot fields start with `favorite_`.)

**Comment by timokleemann** [comment]
By the way, I also set `config.spinner_enabled` to `false` since I have **two** forms on **one** page and the validator keeps complaining about the duplicate IDs of those two spinners. So let's see how that goes...

So this would be another feature request of mine: Give each spinner a **unique ID** automatically, just in case you have two of them on one page.

**Comment by markets** [comment]
> Give each spinner a unique ID automatically, just in case you have two of them on one page. Right now, each spinner simply gets an ID of "spinner" which is not unique.

That probably makes sense, I'll take a look asap. If you want to give a try, the code that renders this input is this one 👇🏼:

https://github.com/markets/invisible_captcha/blob/ba9e5976d096dba42cae634e02be7afae7912d03/lib/invisible_captcha/view_helpers.rb#L60

**Comment by timokleemann** [comment]
I have to confess that I am really not good at developing gems / plugins. So I'm afraid to mess up your code :see_no_evil:

But if the IDs on the spinners are not even needed (?), they might even be removed entirely, so the change would be fairly simple: 

`hidden_field_tag("spinner", session[:invisible_captcha_spinner], :id => nil)`

If they *are* required, it's probably a good idea to add some kind of timestamp or random number to them, so each one will be unique.

**Comment by markets** [comment]
@timokleemann that ID is not used internally and it's not mandatory for valid HTML, so yeah I think we can just set it to `nil`.

Gonna close this issue, I moved the relevant info to #115. Thanks!
