### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by kikito** [markets/invisible_captcha#12]
I would like to be able to use this gem in a multi-lingual environment.

I can give it a try at making a PR integrating it with i18n if you think it is worth it.

**Comment by markets** [comment]
hi @kikito,

Thanks for your suggestion. But I'm not sure whether it is worth... The gem uses just a couple of strings:

- sentence_for_humans: text for real users, just in case the honeypot is visible (kind of fallback)
- timestamp_error_message: error message (flash message) when threshold is reached

And ideally a real user shouldn't see those messages frequently ... 😅  

Would be enough (IMHO) to achieve that with:

```ruby
# config/initializers/invisible_captcha.rb
InvisibleCaptcha.setup do |config|
  config.sentence_for_humans = I18n.t("your_translation_key")
end
```

But locales are loaded after the initializers... so it doesn't work.

Anyway, if the integration is "easy" and doesn't involve much code, we could assess the idea, why not? What do you think?

On the other hand, I'm preparing a new release here: #8. Any kind of feedback is much appreciated.

PS. Buen trabajo estáis haciendo con el proyecto de Consul 👍

**Comment by kikito** [comment]
Hi again,

The thing that worries me is screenreaders. I am not familiar with them but I must assume that at least some of them will read the "sentence for humans" aloud.

In order to make it compatible with the current implementation, it would have to accept a block in the initializer:

``` ruby
# config/initializers/invisible_captcha.rb
InvisibleCaptcha.setup do |config|
  config.sentence_for_humans = { I18n.t("your_translation_key", "default value") }
end
```

But ideally it should accept strings too to make it compatible with existing implementations.

I think the PR will be small enough.

> On the other hand, I'm preparing a new release here: #8. Any kind of feedback is much appreciated.

My view, especially in pre-1.0 releases, is: "release early, release often". I think the current state is good enough for making a new release. Any missing docs, etc can come in a 0.8.1 release if you want.

> Buen trabajo estáis haciendo con el proyecto de Consul 👍 

Gracias! La idea es usar `invisible_captcha` en Consul :)

**Comment by markets** [comment]
Hi @kikito, thanks a lot for your feedback and thoses PRs 💯

I have some free time tomorrow, so I'll review, merge and cut a new version.
