### ISSUE TITLE
 [Invisible Captcha] Potential spam detected for IP 127.0.0.1. Timestamp not found in session.

### ISSUE THREAD

**Issue by mices** [markets/invisible_captcha#127]
I'm using tags without honeypot attribute and check_captcha only: [:create] in my devise/users/registrations_controller.rb without any initializer file

**Comment by markets** [comment]
Hello @mices

`check_captcha` this method is not provided by this gem, are you sure you read the [docs](https://github.com/markets/invisible_captcha#usage)?

**Comment by mices** [comment]
Sorry typo that's what I mean I solved the problem by using   <%= f.invisible_captcha %> in my form  but on a different site I'm getting an error
Unpermitted parameter: :k-zarohdyebjlxtg. Context: { controller: Users::RegistrationsController, action: create, request: #<ActionDispatch::Request:0x00007fda81582920>, params: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"abc@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "k-zarohdyebjlxtg"=>""}, "spinner"=>"4bc574db7c3c40be0bd4a33dd2b774f7", "commit"=>"Sign Up", "controller"=>"users/registrations", "action"=>"create"} }

**Comment by markets** [comment]
Is this app open source? If so,I'll take a look. It's hard to debug an error without having access to the code. I'd say you can pass a custom honeypot name and then specify it in the controller via the `honeypot` option.

**Comment by mices** [comment]
What could cause it to raise unpermitted parameter with the gem installed?

**Comment by mices** [comment]
It's rejected a param named spinner that I don't know what it is so i tried using   "invisible_captcha only: [:create], honeypot: :spinner" but I don't know what spinner is or what I'm doing
09:27:02 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"123", "email"=>"123@123.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "brksd-pmugjxc"=>""}, "spinner"=>"35be9ca7be884d125ebe9a978b2b9b1b", "commit"=>"Sign Up"}
09:27:02 web.1  | [Invisible Captcha] Potential spam detected for IP 127.0.0.1. Timestamp not found in session.

**Comment by mices** [comment]
are you sure it shouldn't be <%= f.invisible_captcha %> I get error either way though

**Comment by markets** [comment]
The spinner is an extra check this gem does under the hood. 

You have 2 options:
- passing a custom honeypot name, then you need to specify it in the controller
- use the default honeypots, no need to specify them in the controller macro

Both solutions work fine, but you shouldn't use the "honeypot: :spinner", as the spinner is used for an extra internal check.

**Comment by mices** [comment]
I tried that by using a random honeypot name :abcdefg and put in controller and view and it failed with incorrect spinner value Then I took out the references to honeypot from controller and view and got the error Unpermitted parameter: :vkwxpsiuqc-eagr In this case I used <%= f.invisible_captcha %>

**Comment by markets** [comment]
It's really hard to debug this installation with no access to the source code 😅 ...

Maybe you can disable the spinner extra check for now? This can be done by the global setting `config.spinner_enabled = false`.

**Comment by mices** [comment]
Could it be because my model has a lot of directives in it like searchkick

**Comment by mices** [comment]
I can post my model, view or controller Which should I share?

**Comment by markets** [comment]
The ideal solution is to create a minimal reproducible example app to facilitate the work for the maintainers. If you just share some parts, maybe some non-posted (config, other gems, ...) code is the root cause of the problem.

If you need priority support, you can also sponsor me: https://github.com/sponsors/markets

**Comment by mices** [comment]
I got it working by disabling spinner but could I have whitelisted it in params.require(:user).permit(... in the controller?

**Comment by markets** [comment]
Not sure why you want to whitelist the honeypot attribute, as it does not need to be passed to the create/update methods. 

The gem by itself already does some parameters clean-up:

https://github.com/markets/invisible_captcha/blob/1b70b6ee9351681800e10627411ef9e71be0220f/lib/invisible_captcha/controller_ext.rb#L96
