### ISSUE TITLE
Captcha field visible in Rails 7.1 

### ISSUE THREAD

**Issue by cimm** [markets/invisible_captcha#130]
We have been using invisible_captcha for a while now, and it has been working great. When upgrading from Rails 7.0 to 7.1, I noticed the captcha field is now visible in the browser. This obviously defeats the purpose of the honeypot field.

The following HAML snippet

```haml
= form_for resource, as: resource_name, url: registration_path(resource_name) do |f|
  = f.invisible_captcha :nickname, nonce: true
```

rendered in Firefox in Rails 7.0

![image](https://github.com/markets/invisible_captcha/assets/68112/87cf1231-2748-40d3-b9a0-be36182b70e9)

but rendered in Rails 7.1

![image](https://github.com/markets/invisible_captcha/assets/68112/094b54f7-583d-423a-8786-f74c032a97da)

Notice the main `<div>` no longer wraps the honeypot field. Same result in Chromium. Maybe related with the new Rails 7.1 HTML5 sanitizer?

Anyone else seeing this in Rails 7.1?

**Comment by markets** [comment]
Hey @cimm Could you please try to reproduce it in the [demo app](https://github.com/markets/invisible_captcha?tab=readme-ov-file#demo)?

**Comment by markets** [comment]
Hello @cimm I just added (https://github.com/markets/invisible_captcha/commit/cee6fdf0cdc56ba4737f7d0b763ad20c8d8facf6) Rails 7.1 in our CI and tests are passing ✅ 

On the other hand, I just run the [demo app](https://github.com/markets/invisible_captcha?tab=readme-ov-file#demo) under Rails 7.1 and I can't reproduce it. Maybe "the new Rails 7.1 HTML5 sanitizer" is offered via some configuration flag?

**Comment by cimm** [comment]
Hi @markets. Good to hear!

I tried the demo app but couldn't get it up and running in time (computer issues, nothing related to the app), so I should give it another try.

Our Rails app has been upgraded from many versions ago, so maybe there is some setting somewhere that is different from a default Rails 7.1 app. I will close this issue and report back when I can pinpoint the issue.

Thanks for the help.

**Comment by cimm** [comment]
A week later. We fully migrated to Rails 7.1, meaning we now activate all the Rails 7.1 framework defaults. We added the gem again, and it works with no issues whatsoever! I'm not sure if it was related to the framework defaults, but I'm happy to report that my issue was misguided.

Thanks for the help, and I'm sorry to have taken your time. :pray:

**Comment by markets** [comment]
No prob @cimm! Thanks for confirming 🤝
