### ISSUE TITLE
Support for Invisible Captcha with Stimulus Reflex and Service-Driven Form Submissions

### ISSUE THREAD

**Issue by OscarGonzalez97** [markets/invisible_captcha#139]
I'm trying to implement Invisible Captcha in a form that uses Stimulus Reflex for submissions. In my setup, the form directly triggers a Reflex that interacts with a service to handle the object creation logic, bypassing the typical controller flow.

The challenge is that while the Invisible Captcha field is present in the form, it doesn't trigger any validation when the form is submitted via the Reflex (because it is not configured, of course). Since the form submission is handled by Reflex and a service and not the controller, the captcha verification is skipped altogether.

**Comment by markets** [comment]
Hello @OscarGonzalez97 👋

Sorry, I've never used Stimulus Reflex so I have no idea how it works internally. If you want to explore what's needed to support it, feel free to investigate and propose a path, I'll happy to discuss about it. 

The main logic is actually in this module: https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb. As you can see, it is currently designed to be injected in a Rails controller.

By the way, if big changes will be necessary to make it work, I'm probably -1, as we can't support any framework out there and adapt this code to their internals.

**Comment by n-studio** [comment]
@markets It seems the invisible captcha doesn't work out of the box for ajax queries (timestamp + spinner).

I think the readme should include instructions on how to implement a proper ajax query and these instructions could be easily reused for Stimulus Reflex.

**Comment by markets** [comment]
@n-studio There is a NOTE at the end of this section https://github.com/markets/invisible_captcha?tab=readme-ov-file#usage, but please feel free to propose any enhancement.

**Comment by n-studio** [comment]
@markets Ok! I'll try to make it work and then push a PR with instructions.
