### ISSUE TITLE
`root_path` doesn't exist in some apps

### ISSUE THREAD

**Issue by dnsos** [markets/invisible_captcha#140]
In Rails apps that act as multi tenant/platform apps, the one `root_path` may not exist, instead there may be multiple root paths such as `platform_a_root_path`, `platform_b_root_path`, etc.

This causes the [`on_timestamp_spam` method](https://github.com/markets/invisible_captcha/blob/b0093de90621f8362223f28ce51fe57e9f067d7d/lib/invisible_captcha/controller_ext.rb#L32) to throw an error when executed:

```bash
undefined local variable or method `root_path' for an instance of [...]
```

This is certainly a bit of an edge case but the issue could be prevented by changing the method like this:

```diff
def on_timestamp_spam(options = {})
  if action = options[:on_timestamp_spam]
    send(action)
  else
    flash[:error] = InvisibleCaptcha.timestamp_error_message
-  redirect_back(fallback_location: root_path)
+  redirect_back(fallback_location: "/")
  end
end
```

If that's a possibility, I'm happy to provide a PR. Let me know what you think.

**Comment by markets** [comment]
It really seems an edge case:
- Because in a regular workflow you will be redirected back, this is only a fallback
- Maybe some apps don't have "/" path neither?

**Comment by elalemanyo** [comment]
@markets Maybe we can add `redirect_fallback_path` option 🤔

https://github.com/markets/invisible_captcha/pull/141

**Comment by markets** [comment]
@dnsos @elalemanyo Sorry but I'm not aligned with the changes proposed here: https://github.com/markets/invisible_captcha/pull/141#issuecomment-2493296042. 

Maybe it's ok something simpler like: `defined?(root_path) ? root_path : '/'`, but I'm -1 to provide new configuration options for that.

**Comment by dnsos** [comment]
> Maybe it's ok something simpler like: defined?(root_path) ? root_path : '/'

@markets I like it, it's simple and does the trick.

---

Additional context from my scenario: It _is_ an edge case, but at the moment that edge case can only be handled by monkey patching the default `on_timestamp_spam` method. `redirect_back(fallback_location: root_path)` might only use the fallback location in rare-ish cases, but it throws the error before there is a chance to evaluate the redirect back: The attempt to set the fallback location via `root_path` gets in the way.

**Comment by markets** [comment]
Ah yeah, got it! Then I think we can go with the simple patch proposed in https://github.com/markets/invisible_captcha/issues/140#issuecomment-2493305068.
