### ISSUE TITLE
Add if option to controller action?

### ISSUE THREAD

**Issue by bendangelo** [markets/invisible_captcha#143]
I have a case where I want the sign up form to have a invisible captcha but on the json version to disable it. This would work if there was a way to disable it conditionally.

**Comment by bendangelo** [comment]
I just found out unless and if can be used. I think this should be documented.

**Comment by markets** [comment]
Hey @bendangelo 👋

That's already documented here: https://github.com/markets/invisible_captcha?tab=readme-ov-file#controller-method-options.
