### ISSUE TITLE
timestamp stored as a string in the session

### ISSUE THREAD

**Issue by kikito** [markets/invisible_captcha#16]
I am getting the following error when using the timestamp function in 0.8.1:

```
NoMethodError:
       undefined method `-@' for "2016-04-25T12:53:49.173+02:00":String
     # /Users/kikito/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/core_ext/time/calculations.rb:142:in `ago'
     # /Users/kikito/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/time_with_zone.rb:265:in `rescue in -'
     # /Users/kikito/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/time_with_zone.rb:265:in `-'
     # /Users/kikito/.rvm/gems/ruby-2.2.3/gems/invisible_captcha-0.8.1/lib/invisible_captcha/controller_ext.rb:41:in `invisible_captcha_timestamp?'
```

I believe that the problem is that rails stores the values in `session` as strings; so even when `invisible_captcha` does `session[:invisible_captcha_timestamp] ||= Time.zone.now`, the value is later returned as a string (`"2016-04-25T12:53:49.173+02:00"`).

Let me see if I can prepare a PR to fix this

**Comment by markets** [comment]
hi @kikito, yep, you're right, the `session` object is just a string key-value store.
