### ISSUE TITLE
The default timestamp action doesn't cancel the form submission

### ISSUE THREAD

**Issue by kikito** [markets/invisible_captcha#18]
Currently the default action taken when a timestamp is detected only adds an error message to the flash, and adds a message on the log. But critically, the "fast action" does not get cancelled - despite the flash message and the logged error, the form is saved unless `on_timestamp_spam` is set to something which does a `render` or a `redirect`.

I think it is odd that the default behavior is "leave the fast requests in" (and log/flash instead).

Most of the time the desirable action will be either a `render :new` or a `render :edit`, but this won't work all the time. I suggest adding a `redirect_to root_path` on the default timestamp action to prevent this. This works all the time and will shield the app against SPAM by default.

What do you think?

**Comment by markets** [comment]
Yes, you're totally right @kikito, let's continue the discussion in the attached PR.
