### ISSUE TITLE
allow to deactivate timestamp_threshold

### ISSUE THREAD

**Issue by schugabe** [markets/invisible_captcha#20]
For rspec tests I set timestamp_threshold=0 to disable the timestamp check.
But the check for a timestamp in the session is still executed and so all the rspec tests fail (because the timestamp in the session is never set).

I'd suggest to skip this check completely if the threshold is set to zero.

**Comment by markets** [comment]
Thanks for reporting @schugabe. 

If I understand you correctly, you want to skip the check during the tests, as you are doing controller testing and timestamp in session isn't set. In that case you are entering this block: https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb#L42-L46, am I right? 

Outside testing, this check are totally valid...but it make sense to make it "de-activable" per environtment. To achieve that, we have some options:

1) set `InvisibleCaptcha.timestamp_threshold = 0`
2) add a new flag to deactivate the timestamp check (something like `InvisibleCaptcha.timestamp_enabled = false`)

IMO, option 2, feels probably more clear, what do you think?

**Comment by schugabe** [comment]
Yes option 2 would be more clear!

Currently the check in line https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb#L43 is done even if InvisibleCaptcha.timestamp_threshold=0
I created a pull request for a test that is currently failing #21

**Comment by markets** [comment]
Hi @schugabe, I'll take a closer look this week, but I think we should move on option 2. What do you propose to fix the failing test in that PR? In my opinion, we just need to introduce this new option to disable the timestamps. Thanks!

**Comment by schugabe** [comment]
I also prefer an dedicated option to disable this check completely. This would also fix the failing test.
So option 2 is the way to go :+1:

**Comment by markets** [comment]
ok @schugabe, but in that case, we don't need to support `timestamp_threshold = 0` to disable this check. Semantically, it's correct, "wait 0 seconds" is going to fail always... so the test will be written using the new flag `timestamp_enabled = false`. 

Are you agree with that? (If yes, we can close that PR #21 and rename this issue to something like: "Allow to disable the timestamp check")

**Comment by schugabe** [comment]
Yes I agree with that

**Comment by markets** [comment]
@schugabe New version pushed https://rubygems.org/gems/invisible_captcha/versions/0.9.1 👏 👏 👏
