### ISSUE TITLE
How to test by manually filling in the invisible form

### ISSUE THREAD

**Issue by chickensmitten** [markets/invisible_captcha#3]
Hey markets,

I am wondering if there is a way for me to manually fill in the form to test this?

Thanks.

**Comment by markets** [comment]
Hey @chickensmitten, sorry for the delay, vacations time :smile: 

Yes, you can achieve that using the initializer (`config/initializers/invisible_captcha.rb`):

```ruby
InvisibleCaptcha.setup do |config|
  config.visual_honeypots = true # default is false
end
```

This option make honeypots visible, useful to test/debug your implementation.

**NOTE** Don't forget to restart the server after changing code under initializers.

**Comment by chickensmitten** [comment]
Hey there, looks cool. =) works like a charm.
