### ISSUE TITLE
doesn't work with devise ?

### ISSUE THREAD

**Issue by jimchild49** [markets/invisible_captcha#37]
I have tried this gem with devise so far and it seems not working, in the registration form I added 

 `<%= f.invisible_captcha :usernote %>`

Then in my custom RegistrationsController I added 

```
invisible_captcha only: [:create], honeypot: :usernote, on_spam: :spam_callback_method

private

    def spam_callback_method
        throw "spaaaaam"
    end
```

When I submit the form and I add value="something" to the hidden captcha field , the registration work fine and nothing happen ! I thought maybe something is wrong with the callback, so I just added 

`before_action :spam_callback_method, only: :create`

and the callback seems working fine :) so I think maybe there is something going wrong there!

**Comment by 99cm** [comment]
it looks your views code incomplete, missing action part.

**Comment by markets** [comment]
Hi :wave: I think the point is: you're using the form helper `f.invisible_captcha :usernote`, this automatically adds an scope, like `user[usernote]`, in your input name. So you can solve this in a couple of ways:

- define the scope in the controller as well ([doc](https://github.com/markets/invisible_captcha#controller-method-options)):

    `invisible_captcha only: [:create], honeypot: :usernote, scope: :user, on_spam: :spam_callback_method`

(check/inspect what html produces your helper in the form)

- use the view helper without the `f.` part, to send an "unscoped" param :

    `<%= invisible_captcha :usernote %>`

---
I think both options will solve your integration. Let me know how this goes. Thanks!
