### ISSUE TITLE
Should generated fields be marked 'autocomplete=off'?

### ISSUE THREAD

**Issue by rdlugosz** [markets/invisible_captcha#42]
Just ran into an issue where a legit user had filled an invisible_captcha field... I assume it was an auto-fill situation because we had named the field "name". Apart from my surprise that a browser would autofill an invisible field (maybe some extension did it?), I'm curious if it would make sense to have the generated tag automatically include an `autocomplete=off` directive. 

Any thoughts one way or another? If you think it'd be a safe addition (meaning that it would not reduce effectiveness of the captcha) I'll code up a PR.

**Comment by markets** [comment]
Hi @rdlugosz yeah, that totally seems an auto-fill issue. 

A priori, this change is similar to proposed and discussed in #38? The point is, adding "clues" in the inputs would make them easier to recognize? But on the other hand, `aria-hidden` seems quite different, in purpose, compared to `autocomplete=off`, which is pretty used in sign-in/sign-up forms.

You can pass [html options](https://github.com/markets/invisible_captcha#view-helpers-options) to the honeypot input, so you can try it out live now:

```
f.invisible_captcha(:subtitle, { autocomplete: 'off' })
```

**Comment by rdlugosz** [comment]
Yea, I agree that this is a little different than the aria tag since autocomplete=off is often declared on form fields. I did enable it in my one-off form and it seems to be fine; I don't really have enough data where I could say whether or not it is impacting the bot hit rate.

**Comment by markets** [comment]
I'll add the `{ autocomplete: 'off' }` option to my sites too, one of them have quite traffic, so we'll have more data and eventually, enable it by default, if the change finally doesn't impact the bot hit rate.

**Comment by rdlugosz** [comment]
awesome! thx.

**Comment by markets** [comment]
@rdlugosz thank you too :+1: 

Release `v0.12.0`https://rubygems.org/gems/invisible_captcha/versions/0.12.0 pushed to RubyGems :rocket:
