### ISSUE TITLE
Clearing session invisible_captcha_timestamp

### ISSUE THREAD

**Issue by summera** [markets/invisible_captcha#49]
Looking through the code, it doesn't look like `invisible_captcha` is clearing the session timestamp in an after filter. Is there a reason for this? Might be a good thing to add in so it's not sitting around in the session.

**Comment by markets** [comment]
Hi @summera and thanks a lot for giving this gem a try! You're right, we actually don't clean up this session timestamp, there is no particular reason that I can remember. Do you have any specific issue so far with that?

**Comment by summera** [comment]
I've turned this feature off for the initial release but would like to try it out in production soon. No specific issues, but it'd be a good thing to clean up to remove unnecessary data from the session. Would you accept a PR that cleans this up?

**Comment by markets** [comment]
:wave: @summera if code changes are "small" and reasonable, I'm ok, but if it is not like that, I'd prefer to avoid an increase in code complexity with no real benefit :smile_cat:

**Comment by summera** [comment]
Opened https://github.com/markets/invisible_captcha/pull/50
