### ISSUE TITLE
Session timestamp is cleared if `render` instead of `redirect`

### ISSUE THREAD

**Issue by njakobsen** [markets/invisible_captcha#53]
If we `render :new` instead of `redirect_to` in the timestamp response, the timestamp stored in the session will be cleared _after_ the form is re-rendered, leaving it blank in the next attempt at submitting.

This is a problem for me in the case where a user fills out everything but gets a validation error, then corrects the error and submits in less than the threshold time. In this case, since the session does not contain a timestamp, the request is deemed to have failed the timestamp check.

It would be great if we could do something to avoid avoid clearing the timestamp in these custom scenarios, e.g.

```ruby
  def timestamp_spam_response
    InvisibleCaptcha.record_timestamp
    render :new
  end
```

What's strange about this issue is that the form we render happens after we delete the timestamp from the session, so it should put it back in.

Occurs in Rails 4.2.0.

**Comment by markets** [comment]
Hi @njakobsen and thanks for trying Invisible Captcha 👍 

Latest version, 0.12.1, shipped with only 1 relevant change:
- Changes: https://github.com/markets/invisible_captcha/blob/master/CHANGELOG.md#0121
- Relevant code: https://github.com/markets/invisible_captcha/pull/50 (From original issue #49)

Some points to check/review 🙏:
1) Can you try with version 0.12.0? Just to confirm latest version isn't causing problems
2) Anyway, as you pointed out, it's strange... https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/view_helpers.rb#L12 => everytime you render the form, we record the timestamp in session via the view/form helper
