### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by jmstfv** [markets/invisible_captcha#55]
@markets 👋 

I have enabled a [Content Security Policy](https://edgeguides.rubyonrails.org/security.html#content-security-policy) but that breaks invisible captcha since inlined CSS changes every second. I can make it work by setting `style-src` to `unsafe-inline` but that's more of a hack.

Is there a way to insert a `nonce` to a generated`<style>` tag?

**Comment by markets** [comment]
Hi @jmstfv 👋 to be honest I didn't tried yet this combination: CSP + invisible_captcha. So not sure what's happening here... 

Couple of comments:
- generated <style> tag doesn't allow any kind of override right now: https://github.com/markets/invisible_captcha/blob/02b9eb97c07f63a7e3f4f2eb5146979d96b46c7f/lib/invisible_captcha/view_helpers.rb#L57
- styles can be injected in <head> using the `injectable_styles` option: https://github.com/markets/invisible_captcha#plugin-options

**Comment by jmstfv** [comment]
I see.

One way of doing it would be adding `html_options` parameter that we could then pass along to the `content_tag`:

    html_options[:nonce] = content_security_policy_nonce if html_options[:nonce] == true
    
    content_tag(:style, media: 'screen', html_options) do


Then users could pass `nonce: true` attribute, just like [here](https://edgeguides.rubyonrails.org/security.html#content-security-policy) (scroll to the bottom of that section).

    <%= injectable_styles nonce: true %>

Here is the sample code that demonstrates that: https://github.com/slim-template/slim/issues/810#issuecomment-526482659

Are you open for a PR?

**Comment by markets** [comment]
Ok @jmstfv PR for CSP support are welcome! 

About the implementation, it's seems fine to me to allow html_options to be passed to the syle TAG, but we should make it work for both options: injectable_styles = true | false.

Maybe we can use the `options` argument, which is passed along the methods:
https://github.com/markets/invisible_captcha/blob/02b9eb97c07f63a7e3f4f2eb5146979d96b46c7f/lib/invisible_captcha/view_helpers.rb#L25 => https://github.com/markets/invisible_captcha/blob/02b9eb97c07f63a7e3f4f2eb5146979d96b46c7f/lib/invisible_captcha/view_helpers.rb#L48

Thanks.
