### ISSUE TITLE
Can't seem to make honeypots work properly

### ISSUE THREAD

**Issue by duartemvix** [markets/invisible_captcha#68]
I've been trying to use honeypots in order to trick bots into using appropriate data for the honeypot field.

However, as I was adding the specific honeypot `:title` into my views and controllers a problem came to surface. The forms are just simply being submitted as if there were no inputs in honeypots.

This is how views look like

`<%= f.invisible_captcha :title, nonce: true, visual_honeypots: true %>`
Nonce is true for Rails 6, honeypot is named :title, and visual_honeypots are set to true to be debugged as of this moment.

This is what controllers look like

`invisible_captcha                                   only: [:create_message, :sign_up],
								scope: ['pages_fan', 'pages_contact'],
								honeypot: :title,
								on_timestamp_spam: 		:spam_callback,
								on_spam: :spam_callback,										 
                                                                timestamp_threshold: 	8`

This is how one of the forms that are being submitted is writtenin html

`<input class="string optional input is-medium" autocomplete="off" placeholder="E-mail" type="text" name="pages_fan[email]" id="pages_fan_email">`

And this is the honeypot input:

`<input type="text" name="pages_fan[title]" id="pages_fan_title" autocomplete="off" tabindex="-1" nonce="true">`

And this is how Rails is generating parameters:

`Parameters: {"authenticity_token"=>"iik9w3MTjfme4fYf0CruqlBfHWhkT+TznNOJEELAX61Ou7s7Fr4SgKOLFaQcNPAEPp+zgO2NF73xdmZmkodoBg==", "pages_fan"=>{"title"=>"mat", "email"=>"m@de.com"}, "commit"=>"Assinar"}`

It seems that the :title attribute is not being read by invisible_captacha and hence why I am having problems preventing spam.

Version details:

invisible_captcha, latest gem version
Rails, version 6.0.2.2
Ruby, version 2.6.1

**Comment by markets** [comment]
Hi @duartemvix and thanks for trying this gem :)
Sorry, I'm not sure if I understand your issue... You are receiving data in the honeypot attribute `"title"=>"mat"`, so this is considered as spam.

**Comment by duartemvix** [comment]
> Hi @duartemvix and thanks for trying this gem :)
> Sorry, I'm not sure if I understand your issue... You are receiving data in the honeypot attribute `"title"=>"mat"`, so this is considered as spam.

It's a great gem and I've used a lot recently. But I have just recently tried to use it in a different way creating a honeypot.

But what happened up there is that whenever I filled `:title` with mat it didn't report as spam. The controller action went straight to its end and finished running.

I'm not sure if there was anything that I was missing.

**Comment by markets** [comment]
Ah ok, I think the problem is caused by this array in the scope definition: `scope: ['pages_fan', 'pages_contact']`. If I'm not wrong, array is not supported here.

**Comment by duartemvix** [comment]
> Ah ok, I think the problem is caused by this array in the scope definition: `scope: ['pages_fan', 'pages_contact']`. If I'm not wrong, array is not supported here:
> 
> https://github.com/markets/invisible_captcha/blob/0448cb324da5b819b6e0079b472411339f49659f/lib/invisible_captcha/controller_ext.rb#L80

I just created two calls to invisible_captcha in controllers. Now they're working.

Thanks for the support! :+1:

**Comment by markets** [comment]
> I just created two calls to invisible_captcha in controllers

👍 

You're welcome!
