### ISSUE TITLE
Random honeypot field name within a scope

### ISSUE THREAD

**Issue by dennis95stumm** [markets/invisible_captcha#71]
It would be nice if the generated honeypot field name could be used in a defined scope. Currently it is not possible, because the controller extension just iterates over the default honeypots https://github.com/markets/invisible_captcha/blob/0448cb324da5b819b6e0079b472411339f49659f/lib/invisible_captcha/controller_ext.rb#L89 without adding the specified `scope`.

**Comment by markets** [comment]
Hi @dennis95stumm and thanks for trying `invisible_captcha`. 

I'm not sure if I get 100% your proposal, but if you want to use the `scope` for the honeypot attribute you can already use the following:

```ruby
# view
<%= form_for(@topic) do |f| %>
  <%= f.invisible_captcha :subtitle %>
<% end %>

# controller
invisible_captcha only: [:create, :update], honeypot: 'subtitle'
```

You can see more controller options here: https://github.com/markets/invisible_captcha#controller-method-options

**Comment by dennis95stumm** [comment]
Hi @markets thanks for the answer. But this isn't that what i want. I want to use the invisible captcha with a **generated field name** in a scope. Something like this:
```rails
# view
<%= form_for(Topic.new) do |f| %>
  <%= f.invisible_captcha %>
<% end %>
```
```rails
# controller
invisible_captcha only: [:create, :update], scope: 'topic'
```

**Comment by markets** [comment]
ok, got it, you'd like to use the default random honeypots, with the `scope` option too. Yes, this is a feature request 😺

**NOTE** You can use the helper, instead of the *form* helper to avoid passing the `nil` value and use the random generated ones:

```html+erb
<%= form_for(Topic.new) do |f| %>
  <%= invisible_captcha %> 
<% end %>
```
