### ISSUE TITLE
redirect_to :back Can Result in No HTTP_REFERER Error

### ISSUE THREAD

**Issue by sshaw** [markets/invisible_captcha#72]
Often times I get the following error when a bot has filled out the form: 

```
An ActionController::RedirectBackError occurred in registrations#create:

  No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].
```

I have no stacktrace with these errors but I think it's coming from [here](https://github.com/markets/invisible_captcha/blob/0448cb324da5b819b6e0079b472411339f49659f/lib/invisible_captcha/controller_ext.rb#L30). 

I don't think Rails 4.2 supports `fallback_location` as an options to `redirect_to` so one must manually check for a referer.

**Comment by markets** [comment]
Hi @sshaw and thanks for reporting. Agree, this surely comes from that line. The method `redirect_back` was introduced in Rails 5, so we can add some manual check to avoid this exception in that code branch, which is for Rails 4 only. Maybe something like this should be enough:

```ruby
redirect_to request.referer || root_path, flash: { error: InvisibleCaptcha.timestamp_error_message }
```

**Comment by markets** [comment]
Closing, `master` (invisible_captcha v2) now supports Rails >= 5.2
