### ISSUE TITLE
"If you are a human, ignore this field" - text is showing in form

### ISSUE THREAD

**Issue by Bsmoder** [markets/invisible_captcha#75]
In works fine most of the time, but in one instance for a customer it was showing the text. Who knows what is the issue. Thanks

![Image from iOS](https://user-images.githubusercontent.com/19339436/89578779-b4044600-d800-11ea-8b5d-f7b62901d5a5.png)

**Comment by markets** [comment]
Hi @Bsmoder 👋 

This gem provides different ways and flags to customize your setup, so we can't help you if you don't provide more info about how this is installed/configured in the app, or a sample app that reproduces the error.

Maybe you can find useful information in the following thread: https://github.com/markets/invisible_captcha/issues/70.

Best,
Marc

**Comment by markets** [comment]
Closing for now @Bsmoder, we can't do anything without more information. Please re-open in case you can provide a sample app that reproduces the error.
