### ISSUE TITLE
Chrome ignoring autocomplete "off" leading to false positives

### ISSUE THREAD

**Issue by andreas-venturini** [markets/invisible_captcha#80]
*references https://github.com/markets/invisible_captcha/issues/42*

We recently updated the label text of the honeypot field to "country". Reviewing the `invisible_captcha.spam_detected` events we found some false positives where the country field had been autocompleted by Google Chrome.

Looking into this further we found that Chrome does not appear to respect the "off" setting for autocomplete, see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility and the linked bug report https://bugs.chromium.org/p/chromium/issues/detail?id=587466

Therefore, the current default of disabling autocompletion is "dangerous" as users might not be aware that changing the text label to a more "common" value might trigger the autocomplete behavior of Chrome.

I think it might make sense to at least add a warning next to the "sentence_for_humans" [plugin option](https://github.com/markets/invisible_captcha#plugin-options) indicating that custom text labels might trigger autocompletion in Chrome and should be tested properly.

There are possible alternatives for autocomplete that can be used, see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete - but each might come w/ it's own disadvantages so they are probably not a sane default choice either.

**Comment by markets** [comment]
Hi @andreas-venturini, yes the "autocomplete" flag is totally a mess still in 2020, each browser and each version can act in different way, so it's hard to settle to some more robust spec.

I agree to add some warning, but not sure about your proposed place. 

On the other hand, remember the you can customize the timestamp threshold (`timestamp_threshold` option) at app level and/or override per controller/action. Sometimes it makes sense to use different values depending on the form (or even disable it in some specific forms). Note that disabling the time-sensitive feature doesn't disable the honeypot check.

**Comment by andreas-venturini** [comment]
> I agree to add some warning, but not sure about your proposed place.

Well as far as I'm concerned the customization option of the text is what will likely cause this "unexpected" behavior so to me it seems natural to add the warning there.

> On the other hand, remember the you can customize the timestamp threshold

Yes, but that has nothing do to w/ the false positive caused by the autocomplete "off" setting, right? Since the honeypot check will still "fail" if Chrome fills out the hidden field.

**Comment by markets** [comment]
> Well as far as I'm concerned the customization option of the text is what will likely cause this "unexpected" behavior so to me it seems natural to add the warning there.

But this `sentence_for_humans` is basically for screen readers only. I think it will fit better in other section, at some point where we talk about the "honeypot".

> Yes, but that has nothing do to w/ the false positive caused by the autocomplete "off" setting, right? Since the honeypot check will still "fail" if Chrome fills out the hidden field.

You're right, it's probably unrelated to this case (the browser autofilling the honeypot input). I just mention it because I also got some false positives in very short forms with the time-sensitive check.

**Comment by andreas-venturini** [comment]
> But this sentence_for_humans is basically for screen readers only (or people with visible honeypots). I think it will fit better in other section, at some point where we talk about the "honeypot".

I get what you're saying and it makes sense when you look at it that way.  However, customizing the `sentence_for_humans` turned out to make a real difference to us in terms of the amount of spam that still gets through - so to me it's a really useful feature to help fine-tune the config.

**Comment by markets** [comment]
That's really weird and I think it will be really hard to settle to something that works for every case/app/situation/attackers... I'm just using the defaults (no `sentence_for_humans` customization) in several apps with quite traffic, with really great success. 

I understand the point of warn users to use a custom honeypot name that probably will be autofilled by the browser, but I can't see how this is related to the label (`sentence_for_humans`). I think we are mixing things:

- first, we are talking about the autofill + false positives
- in your last message, you are talking about how the `sentence_for_humans` tuning helped you to prevent more spam

:sweat_smile: Sorry, not sure what you're finally proposing.

Keep in touch!

**Comment by andreas-venturini** [comment]
> That's really weird

Why do you think that? Do you believe it's unlikely a bot "learns" to ignore labels like *If you are a human, ignore this field*?

> I think it will be really hard to settle to something that works for every case/app/situation/attackers

I agree - and therefore I would not change the default, all the more since it seems to be working well for you.

> I'm just using the defaults (no sentence_for_humans customization) in several apps with quite traffic, with really great success.

In our apps about 95% of spam is blocked, however, out of this only 2-3 % is blocked due to bots filling out the honeypot (in the default configuration). The vast majority is only blocked due to the timeout check. This was surprising for us too - we only realized this after reviewing `invisible_captcha.spam_detected`. It was the reason we started tinkering w/ changing the default config in the first place.

> I understand the point of warn users to use a custom honeypot name that probably will be autofilled by the browser, but I can't see how this is related to the label (sentence_for_humans)

I'm still referring to the **label**, **not** the name of the honeypot field. Maybe that's the misunderstanding here? Just to reiterate -  changing `sentence_for_humans` was what triggered the autocomplete behavior of Chrome **not** changing the name of the honeypot field (we didn't touch the name).

> in your last message, you are talking about how the sentence_for_humans tuning helped you to prevent more spam

Yes, I used this as an example for why I believe the warning should go next to the `sentence_for_humans` option - and that's what I'm still proposing for the reasons written above. 
But that's just my opinion, you are the maintainer and if you feel the warning should be better placed elsewhere by all means, go for it :)

**Comment by markets** [comment]
> Why do you think that? Do you believe it's unlikely a bot "learns" to ignore labels like If you are a human, ignore this field?

Ah no no, not unlikely at all, it's really feasible of course, simply never got this feedback from any user of the gem (and we have big players using this, like GitLab).

> I'm still referring to the label, not the name of the honeypot field. Maybe that's the misunderstanding here?

Yes, I think we got some misunderstanding here, sorry :)) Now I have a cleaner idea about your experience and your suggestion makes sense to me as well. Just a couple of notes:

- this option `sentence_for_humans` uses i18n by default: https://github.com/markets/invisible_captcha#i18n
- it can also be overwritten in the view helper: https://github.com/markets/invisible_captcha#view-helpers-options

**Comment by tmaier** [comment]
I think this issue should be mentioned in the README. Warn to avoid certain field names, e.g. `country`.

**Comment by markets** [comment]
Hi @tmaier 👋🏼  

I'm of course +1 to improve documentation, please feel free to open a PR to propose the changes you think are necessary or helpful for future readers.
