### ISSUE TITLE
Spinner field?

### ISSUE THREAD

**Issue by yoshie902a** [markets/invisible_captcha#84]
Does this gem provide for a spinner field? As described here.. https://nedbatchelder.com/text/stopbots.html

Doing a check on the IP, Timestamp and a secret seems really useful.

**Comment by markets** [comment]
Hi @yoshie902a, 

Unfortunately no, actually this gem offers a couple of checks:

- honeypot
- time sensitive submission 

But that "spinner" thing seems very interesting. I'll consider it for future releases. And, of course, we are open for pull requests.

Thanks,
Marc

**Comment by yoshie902a** [comment]
I issued a pull request. Please review and refactor as needed. I did not write the tests as I could not run rspec.  When I ran rspec spec, I got the following error..

```
/invisible_captcha/spec/dummy/Gemfile not found
No examples found.

When I ran a specific file, I got the same error.

```

I was in the invisible_captcha folder.

**Comment by markets** [comment]
ok! thanks @yoshie902a! I'll take first quick look. 

[Here in the docs](https://github.com/markets/invisible_captcha#development) you can read instructions to run tests.

**Comment by markets** [comment]
@yoshie902a new version v2 pushed 🚀  to RubyGems:
- https://github.com/markets/invisible_captcha/blob/master/CHANGELOG.md#200
- https://rubygems.org/gems/invisible_captcha/versions/2.0.0

Thanks a lot for you work!
